### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by cmarangop** [haimbar/RCMap#1]
Working with RCMap I got the error: Error in dimnames(x) <- dn : length of 'dimnames' [1] not equal to array extent 
When I use the Sample project data all is fine. But, I got the error when using my data. I have 190 statements, 5 sorters, and 5 raters. What could be the solution? Thanks

**Comment by haimbar** [comment]
I imagine that it's due to some problem with the formatting of the input. If you don't mind sharing the data, please do so. You can also email it to me privately, at my UConn email address

**Comment by cmarangop** [comment]
Thank you so much for your response.
We thought that maybe it is something related to the number of statements,
so we reviewed the statement list to reduce it. So, we have two data sets,
and we will share them with you in two separate emails. This is the first
one in which I got the error message "Error in dimnames(x) <- dn : length
of 'dimnames' [1] not equal to array extent".

Thanks in advance for your help.

**Comment by cmarangop** [comment]
And this is the other one in which we got this message: "Error in adj.mat +
vct %*% t(vct) : non-conformable arrays"

We appreciate your assistance in this matter

Kind regards

**Comment by haimbar** [comment]
I think that this error message is also due to a problem with the input data. Once you send me the files, I will debug it. Thanks!

**Comment by cmarangop** [comment]
Did you receive the files?

**Comment by haimbar** [comment]
Not yet. My email is haim.bar@uconn.edu
