### ISSUE TITLE
Error Input Data

### ISSUE THREAD

**Issue by manonkinaupenne** [haimbar/RCMap#4]
Hi

I encounter an error when R is trying to read my csv files. Here is the error:

Sorter  1 : All cards in one pile!
Sorter  1 : Each card in its own pile!
Sorter  2 : All cards in one pile!
Sorter  2 : Each card in its own pile!
Sorter  3 : All cards in one pile!
Sorter  3 : Each card in its own pile!
Sorter  4 : All cards in one pile!
Sorter  4 : Each card in its own pile!
Sorter  5 : All cards in one pile!
Sorter  5 : Each card in its own pile!
Sorter  6 : All cards in one pile!
Sorter  6 : Each card in its own pile!
Sorter  7 : All cards in one pile!
Sorter  7 : Each card in its own pile!
Sorter  8 : All cards in one pile!
Sorter  8 : Each card in its own pile!
Sorter  9 : All cards in one pile!
Sorter  9 : Each card in its own pile!
Sorter  10 : All cards in one pile!
Sorter  10 : Each card in its own pile!
Sorter  11 : All cards in one pile!
Sorter  11 : Each card in its own pile!
Sorter  12 : All cards in one pile!
Sorter  12 : Each card in its own pile!
Sorter  13 : All cards in one pile!
Sorter  13 : Each card in its own pile!
Sorter  14 : All cards in one pile!
Sorter  14 : Each card in its own pile!
Sorter  15 : All cards in one pile!
Sorter  15 : Each card in its own pile!
Sorter  16 : All cards in one pile!
Sorter  16 : Each card in its own pile!
Sorter  17 : All cards in one pile!
Sorter  17 : Each card in its own pile!
Sorter  18 : All cards in one pile!
Sorter  18 : Each card in its own pile!
Sorter  19 : All cards in one pile!
Sorter  19 : Each card in its own pile!
Sorter  20 : All cards in one pile!
Sorter  20 : Each card in its own pile!
Sorter  21 : All cards in one pile!
Sorter  21 : Each card in its own pile!
Sorter  22 : All cards in one pile!
Sorter  22 : Each card in its own pile!
Sorter  23 : All cards in one pile!
Sorter  23 : Each card in its own pile!
Sorter  24 : All cards in one pile!
Sorter  24 : Each card in its own pile!
Sorter  25 : All cards in one pile!
Sorter  25 : Each card in its own pile!
Sorter  26 : All cards in one pile!
Sorter  26 : Each card in its own pile!
Sorter  27 : All cards in one pile!
Sorter  27 : Each card in its own pile!
Sorter  28 : All cards in one pile!
Sorter  28 : Each card in its own pile!
Sorter  29 : All cards in one pile!
Sorter  29 : Each card in its own pile!
Sorter  30 : All cards in one pile!
Sorter  30 : Each card in its own pile!
Sorter  31 : All cards in one pile!
Sorter  31 : Each card in its own pile!
Sorter  32 : All cards in one pile!
Sorter  32 : Each card in its own pile!
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)

It seems like R is readling each line of the SortedCards.csv as a seperate sorter (32 lines), however, I have only 8 sorters. 

Would you be able to help me? 
Many thanks
Manon

**Comment by haimbar** [comment]
Hi,
Can you email me the project files so that I can debug? Thanks!

**Comment by manonkinaupenne** [comment]
Hi

Attached you can find the file.

Many thanks for your quick response!
Manon

Van: haimbar ***@***.***>
Verzonden: woensdag 9 oktober 2024 13:48
Aan: haimbar/RCMap ***@***.***>
CC: Manon Kinaupenne ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [haimbar/RCMap] Error Input Data (Issue #4)


Hi,
Can you email me the project files so that I can debug? Thanks!

-

**Comment by haimbar** [comment]
There was no attachment

**Comment by manonkinaupenne** [comment]
Hi

My apologies. I try again.

Manon

Van: haimbar ***@***.***>
Verzonden: woensdag 9 oktober 2024 20:33
Aan: haimbar/RCMap ***@***.***>
CC: Manon Kinaupenne ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [haimbar/RCMap] Error Input Data (Issue #4)

There was no attachment

**Comment by manonkinaupenne** [comment]
[SortedCards.csv](https://github.com/user-attachments/files/17323929/SortedCards.csv)

**Comment by manonkinaupenne** [comment]
There seems to be an issue with the deliminator because i save the file as .csv seperated comma's but in an txt file there is still a semi-colon

**Comment by haimbar** [comment]
That's right. The delimiter should be comma.
I will add a warning to the code in a near-future update. Thanks!
